version: '3.6'

services:
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
      - ./data:/app/data
      - node_modules:/app/node_modules

  pipeline:
    build: ./pipeline
    env_file:
      - .env
    volumes:
      - ./pipeline:/app
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: arangodb:3.7.3
    env_file:
      - .env
    volumes:
      - arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529

volumes:
  node_modules:
  arangodb:
