version: '3.6'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:2.1.1
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        API_URL: ${API_URL}
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=causasdecorrupcion.org,www.causasdecorrupcion.org
      - LETSENCRYPT_HOST=causasdecorrupcion.org,www.causasdecorrupcion.org
    restart: always

  backend:
    build: ./backend
    command: /bin/bash -c "sleep 5 && gunicorn --workers=2 --threads=4 --worker-class=gthread --access-logfile=- --log-level=debug --bind=0.0.0.0:5000 main:app"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_HOST=api.causasdecorrupcion.org
      - LETSENCRYPT_HOST=api.causasdecorrupcion.org
    depends_on:
      - db
    restart: always

  db:
    image: arangodb:3.7.3
    volumes:
      - arangodb:/var/lib/arangodb3
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_PASSWORD}
      - VIRTUAL_PORT=8529
      - VIRTUAL_HOST=db.causasdecorrupcion.org
      - LETSENCRYPT_HOST=db.causasdecorrupcion.org
    restart: always

  redis:
    image: redis:6.2
    restart: always

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
  arangodb:
