version: '3.6'

services:
  scraper:
    build: ./scraper
    command: node index.js
    volumes:
      - ./scraper:/app
      - ./data:/app/data
      - node_modules:/app/node_modules

  pipeline:
    build: ./pipeline
    volumes:
      - ./pipeline:/app
      - ./data:/app/data

volumes:
  node_modules:
