version: '3.6'

services:
  frontend:
    build: ./frontend
    command: npm run dev
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    ports:
      - 3000:3000

  backend:
    build: ./backend
    command: /bin/bash -c "sleep 5 && gunicorn --workers=2 --threads=4 --worker-class=gthread --bind=0.0.0.0:5000 main:app"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
      - ./data:/app/data
      - node_modules:/app/node_modules

  pipeline:
    build: ./pipeline
    env_file:
      - .env
    volumes:
      - ./pipeline:/app
      - ./data:/app/data
    depends_on:
      - db

  db:
    image: arangodb:3.7.3
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_PASSWORD}
    volumes:
      - arangodb:/var/lib/arangodb3
    ports:
      - 8529:8529

  redis:
    image: redis:6.2

volumes:
  node_modules_frontend:
  node_modules:
  arangodb:
