name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker container
        run: docker-compose build

      - name: Run scraper
        run: docker-compose run --rm scraper bash run.sh

      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: scraper/data/
